algoritmo "semnome"
// Função :
// Autor :
// Data : 12/01/2022
// Seção de Declarações 
var
voto: inteiro
inicio
// Seção de Comandos 
escreval ("Digite seu voto")
leia(voto)

escolha voto
caso 20
        escreval("Você votou em Marcelo Bernart")
caso 30
        escreval("Você votou no Pernalonga")
caso 40
        escreval("Você votou no Patolino")
outrocaso
         escreval("Voto nulo")

fimescolha
//Uso do escolha
fimalgoritmo
