algoritmo "Para"
// Função :
// Autor :
// Data : 25/01/2022
// Seção de Declarações 
var
i,w, start, end: inteiro

inicio
// Seção de Comandos 

escreval("Começo")
leia(start)
escreval("Fim")
leia(end)
escreval("Decremento")
leia(w)

para i de start ate end passo w faca
     escreval(i)
fimpara

//Você pode colocar as variáveis. Invés de inserir os números.

fimalgoritmo
